### ISSUE TITLE
Can't build `SDWebImage/libwebp-Xcode`

### ISSUE THREAD

**Issue by ra1028** [bazel-ios/cocoapods-bazel#13] opened 2020-05-14 10:26 UTC
Hi,
I'm considering to use this tool instead of the way that use binaries of the CocoaPods library built using xcodebuild.

However, I encountered a situation where I couldn't build the library I use.
So far, the library I have found that can't build is [SDWebImage/libwebp-Xcode](https://github.com/SDWebImage/libwebp-Xcode).

<img width="587" alt="Screen Shot 2020-05-14 at 19 25 33" src="https://user-images.githubusercontent.com/7347118/81923476-b3e91580-9618-11ea-90fc-67e5eb6b42cf.png">

I'm also concerned about whether I can install the [Firebase iOS SDK](https://github.com/firebase/firebase-ios-sdk), although I haven't tried it yet.

It would be very helpful if you could do some investigation.
Thanks.

**Comment by segiddins** [comment] 2020-05-19 00:22
Could you please provide a small repo that reproduces the issue? Thanks!

**Comment by ra1028** [comment] 2020-05-19 05:36
@segiddins 
Thanks for your response.

You can simply reproduce this issue by adding the following files for the arbitrary directory.

- Podfile
```ruby
platform :ios, '13.0'
install! 'cocoapods', generate_multiple_pod_projects: true, incremental_installation: true, integrate_targets: false
inhibit_all_warnings!
use_modular_headers!

target 'Frameworks' do
  use_frameworks!

  pod 'libwebp/webp', '~> 1.1.0'
end

plugin 'cocoapods-bazel', {
  rules: {
    'apple_framework' => { load: '@build_bazel_rules_ios//rules:framework.bzl', rule: 'apple_framework' }.freeze,
    'ios_application' => { load: '@build_bazel_rules_ios//rules:app.bzl', rule: 'ios_application' }.freeze,
    'ios_unit_test' => { load: '@build_bazel_rules_ios//rules:test.bzl', rule: 'ios_unit_test' }.freeze
  }.freeze,
}
```

- WORKSPACE
```bazel
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "build_bazel_rules_ios",
    sha256 = "d8cf3735e5479c420f0ee5bc3aa2394a28ef7b0102a8794c408a5a34604f354d",
    strip_prefix = "rules_ios-0ee2eb52dbec3bb0fb3e04675ea3aa556f1f4f59",
    url = "https://github.com/bazel-ios/rules_ios/archive/0ee2eb52dbec3bb0fb3e04675ea3aa556f1f4f59.tar.gz",
)

load(
    "@build_bazel_rules_ios//rules:repositories.bzl",
    "rules_ios_dependencies",
)

rules_ios_dependencies()
```

- Gemfile
```ruby
source 'https://rubygems.org'

gem 'cocoapods', '~> 1.9.1'
gem 'cocoapods-bazel', github: 'bazel-ios/cocoapods-bazel', ref: 'e1a7f1756ac1434748d6308184b85ce693c426e1'
```

and then hit the following commands.
```sh
bundle config set path vendor/bundle && bundle install
bundle exec pod install
bazel build //Pods/libwebp
```

Thanks,

**Comment by segiddins** [comment] 2020-05-19 18:17
The issue here seems to be

```json
  "pod_target_xcconfig": {
    "USER_HEADER_SEARCH_PATHS": "$(inherited) ${PODS_ROOT}/libwebp/ ${PODS_TARGET_SRCROOT}/"
  },
```

being incorrectly translated to 

```starlark
xcconfig = {"USER_HEADER_SEARCH_PATHS": [
        "/libwebp/",
        "",
    ]},
```

so you'll probably want to take a look at the xcconfig translation code, I don't think I'll have an opportunity to look into this for a while

**Comment by ra1028** [comment] 2020-05-20 03:37
@segiddins 
It's unfortunate for me...
If you can improve it to support environment variables like `PODS_ROOT` or `PODS_TARGET_SRCROOT` I think it very helps the many of libraries.
I'll give up on using cocoapods-bazel for now.
Anyway, thanks for your investigation.

**Comment by segiddins** [comment] 2020-05-20 20:17
We'd be happy to review a PR adding support!

**Comment by thiagohmcruz** [comment] 2021-01-06 14:29
Should we close this?

**Comment by luispadron** [comment] 2022-04-26 19:47
I just ran into this issue as well, specifically when building a snapshot test framework because it defines some `env` vars:

```starlark
env = {
    "FB_REFERENCE_IMAGE_DIR": "$(PODS_TARGET_SRCROOT)/SnapshotTests/ReferenceImages/",
    "IMAGE_DIFF_DIR": "$(PODS_TARGET_SRCROOT)/SnapshotTests/ImageDiffs/",
},
```

I'd be happy to contribute a fix for this if I can get pointed in the right direction 🙏🏼 @thiagohmcruz @segiddins.

**Closed** 2022-05-11 14:32 UTC
